### PR TITLE
feat: added layout and settings form

### PR DESCRIPTION
**Pull request by siddharth952**
Screen Shot 2019-12-23 at 7 47 18 PM

Screen Shot 2019-12-23 at 7 48 27 PM

### CODE REVIEW

**Comment by siddharth952** [comment]
Review this, please. 
@iamareebjamal @adityastic

**Comment by adityastic** [comment]
@siddharth952 great job. Let us for now, not try to follow the material guidelines. Let's try to adapt the HIG standards. Settings look perfect, whereas the main screen, not so much. Let's remove the clipart button next to the textfield and keep a single button for transferring the text to the badge

**Comment by adityastic** [comment]
Also, let's not use buttons with a shadow. Later we'll adapt to some nice interface for sure

**Comment by siddharth952** [comment]
Made the necessary changes

Screen Shot 2019-12-23 at 11 44 30 PM

**Pull request merged**
